Support more constraints for Conway witnesses
input-output-hk/cardano-api pull request #137
Opened 2023-07-25 13:51 UTC by newhoggy

# Changelog

```yaml
- description: |
    Support more constraints for Conway witnesses
    - `conwayEraOnwardsConstraints`
    - `shelleyToBabbageEraConstraints`
  compatibility: compatible
  type: feature
```

# Context

The `Cardano.Api.Query.Types` module was introduce to break cyclic module dependency.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] The change log section in the PR description has been filled in
- [ ] New tests are added if needed and existing tests are updated.  These may include:
  - golden tests
  - property tests
  - roundtrip tests
- [ ] The version bounds in `.cabal` files are updated
- [ ] CI passes. See note on CI.  The following CI checks are required:
  - [ ] Code is linted with `hlint`.  See `.github/workflows/check-hlint.yml` to get the `hlint` version
  - [ ] Code is formatted with `stylish-haskell`.  See `.github/workflows/stylish-haskell.yml` to get the `stylish-haskell` version
  - [ ] Code builds on Linux, MacOS and Windows for `ghc-8.10.7` and `ghc-9.2.7`
- [ ] The changelog section in the PR is updated to describe the change
- [ ] Self-reviewed the diff

# Note on CI
If your PR is from a fork, the necessary CI jobs won't trigger automatically for security reasons.
You will need to get someone with write privileges.  Please contact IOG node developers to do this
for you.

2023-07-25 16:47 UTC, Jimbo4350 requested changes

2023-07-25 16:47 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Feature/ShelleyToBabbageEra.hs
> +  ( FromCBOR (DebugLedgerState era)
This is a bad idea. We were bitten by this in the tracing instances recently.

2023-07-26 13:52 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Feature/ShelleyToBabbageEra.hs
> +  ( FromCBOR (DebugLedgerState era)
Can you elaborate how we were affected by this instance?

2023-07-26 15:03 UTC, Jimbo4350 approved these changes

2023-07-26 15:22 UTC, merged