CIP-1694 CLI stage 1
input-output-hk/cardano-api pull request #14
Opened 2023-05-23 12:01 UTC by newhoggy

# Description

This represents the MVP for [CIP-1694](https://github.com/cardano-foundation/CIPs/blob/e96681908fd336702b9d89827063a190c5656eab/CIP-1694/README.md)

The work for this PR has been moved to https://github.com/input-output-hk/cardano-cli/pull/15

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated.  These may include:
  - golden tests
  - property tests
  - roundtrip tests
  - integration tests
  See [Runnings tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] Any changes are noted in the `CHANGELOG.md` for affected package
- [ ] The version bounds in `.cabal` files are updated
- [ ] CI passes. See note on CI.  The following CI checks are required:
  - [ ] Code is linted with `hlint`.  See `.github/workflows/check-hlint.yml` to get the `hlint` version
  - [ ] Code is formatted with `stylish-haskell`.  See `.github/workflows/stylish-haskell.yml` to get the `stylish-haskell` version
  - [ ] Code builds on Linux, MacOS and Windows for `ghc-8.10.7` and `ghc-9.2.7`
- [ ] Self-reviewed the diff

# Note on CI
If your PR is from a fork, the necessary CI jobs won't trigger automatically for security reasons.
You will need to get someone with write privileges.  Please contact IOG node developers to do this
for you.

2023-05-24 01:03 UTC, CarlosLopezDeLara requested changes

2023-05-24 01:03 UTC, CarlosLopezDeLara commented on cardano-cli/test/cardano-cli-golden/files/golden/help/governance_vote_view.cli
looks good!

2023-05-24 01:03 UTC, CarlosLopezDeLara commented on cardano-cli/test/cardano-cli-golden/files/golden/help/stake-address.cli
Not needed for 8.2 

Later it should be 

cardano-cli stake-address 
            ( key-gen
            | build
            | key-hash
            | registration-certificate
            | deregistration-certificate
            | pool-delegation-certificate
            | drep-delegation-certificate
            )

2023-05-24 01:03 UTC, CarlosLopezDeLara commented on cardano-cli/test/cardano-cli-golden/files/golden/help/stake-address.cli
And then we also need 

cardano-cli stake-address drep-delegation-certificate
( --stake-verification-key STRING
| --stake-verification-key-file FILE
| --stake-script-file FILE
| --stake-address ADDRESS
)
( --drep-verification-key STRING
| --drep-id DREP_ID
)
--out-file FILE

2023-05-24 01:03 UTC, CarlosLopezDeLara commented on cardano-cli/test/cardano-cli-golden/files/golden/help/stake-address_pool-delegation-certificate.cli
Looks good!

2023-05-24 01:03 UTC, CarlosLopezDeLara commented on cardano-cli/test/cardano-cli-golden/files/golden/help/transaction_build-raw.cli
looks good!

2023-05-24 01:03 UTC, CarlosLopezDeLara commented on cardano-cli/test/cardano-cli-golden/files/golden/help/transaction_build.cli
looks good!

2023-05-24 01:04 UTC, CarlosLopezDeLara requested changes
Lefts comments with the required changes. Thank you!!!

2023-05-24 03:57 UTC, newhoggy commented on cardano-cli/test/cardano-cli-golden/files/golden/help/ccm.cli
Done!

2023-05-25 09:33 UTC, newhoggy commented on cardano-cli/test/cardano-cli-golden/files/golden/help/ccm_key-gen-VRF.cli
This is gone now.

2023-05-25 16:37 UTC, disassembler requested changes

2023-05-25 16:37 UTC, disassembler commented on cardano-cli/src/Cardano/CLI/Shelley/Commands.hs
> +  | CcNewCounter
should not exist. CC doesn't run nodes, so no opcert/KES.

2023-05-25 16:37 UTC, disassembler commented on cardano-cli/test/cardano-cli-golden/files/golden/help.cli
> +            ( --stake-verification-key STRING
these don't make sense. No reason to pass a stake credential to a governance action.

2023-05-25 16:37 UTC, disassembler commented on cardano-cli/test/cardano-cli-golden/files/golden/help.cli
> +  Create a key pair for a CCM VRF operational key
Committee doesn't have VRF

2023-05-25 16:37 UTC, disassembler commented on cardano-cli/test/cardano-cli-golden/files/golden/help.cli
> +            ( --stake-pool-verification-key STRING
committee doesn't have counter

2023-05-25 16:37 UTC, disassembler commented on cardano-cli/test/cardano-cli-golden/files/golden/help.cli
> +Usage: cardano-cli governance committee issue-op-cert
committee doesn't have opcert

2023-05-25 16:37 UTC, disassembler commented on cardano-cli/test/cardano-cli-golden/files/golden/help.cli
> +Usage: cardano-cli governance committee register-hot-key
can't reigster your own committee key. Can only be done by an action in phase 2 or embedded in conway genesis.

2023-05-25 16:49 UTC, CarlosLopezDeLara requested changes

2023-05-25 16:49 UTC, CarlosLopezDeLara commented on cardano-cli/test/cardano-cli-golden/files/golden/help/governance_committee_issue-op-cert.cli
We don't need an operational certificate nor a opcert counter

2023-05-25 16:49 UTC, CarlosLopezDeLara commented on cardano-cli/test/cardano-cli-golden/files/golden/help/governance_committee_key-gen-hot.cli
We don't need to produce an operational certificate counter file. It is not required.

2023-05-25 16:49 UTC, CarlosLopezDeLara commented on cardano-cli/test/cardano-cli-golden/files/golden/help/governance_committee_new-counter.cli
Please remove. We don't need a counter therefore we don't need to produce a new one =)

2023-05-25 16:49 UTC, CarlosLopezDeLara commented on cardano-cli/test/cardano-cli-golden/files/golden/help/governance_committee_unregister-hot-key.cli
I think it will be better to rename to `resign-hot-key` See this thread https://input-output-rnd.slack.com/archives/C057E9CJTPH/p1685008094372459?thread_ts=1684866116.549819&cid=C057E9CJTPH

2023-05-26 06:20 UTC, newhoggy commented on cardano-cli/test/cardano-cli-golden/files/golden/help/ccm_issue-op-cert.cli
Removed

2023-05-26 06:20 UTC, newhoggy commented on cardano-cli/test/cardano-cli-golden/files/golden/help/ccm_key-hash-VRF.cli
Removed

2023-05-26 06:21 UTC, newhoggy commented on cardano-cli/test/cardano-cli-golden/files/golden/help/ccm_new-counter.cli
Removed

2023-05-26 06:23 UTC, newhoggy commented on cardano-cli/test/cardano-cli-golden/files/golden/help/governance.cli
This is what I have:

```
Usage: cardano-cli governance
            ( create-mir-certificate
            | create-genesis-key-delegation-certificate
            | action
            | committee
            | drep
            | vote
            | create-update-proposal
            | create-poll
            | answer-poll
            | verify-poll
            )
```

2023-05-26 06:24 UTC, newhoggy commented on cardano-cli/test/cardano-cli-golden/files/golden/help/governance_action_create-constitution-update.cli
This has been moved to stage-2.

2023-05-26 06:24 UTC, newhoggy commented on cardano-cli/test/cardano-cli-golden/files/golden/help/governance_action_create-hard-fork-initiation.cli
This has been moved to stage-2.

2023-05-26 06:25 UTC, newhoggy commented on cardano-cli/test/cardano-cli-golden/files/golden/help/governance_action_create-new-committee.cli
This has been moved to stage-2.

2023-05-26 06:25 UTC, newhoggy commented on cardano-cli/test/cardano-cli-golden/files/golden/help/governance_action_create-no-confidence-motion.cli
This has been moved to stage-2.

2023-05-26 06:26 UTC, newhoggy commented on cardano-cli/test/cardano-cli-golden/files/golden/help/governance_action_create-protocol-parameter-update.cli
This has been moved to stage-2.

2023-05-26 06:26 UTC, newhoggy commented on cardano-cli/test/cardano-cli-golden/files/golden/help/governance_action_create-treasury-withdrawal.cli
This has been moved to stage-2.

2023-05-26 06:31 UTC, newhoggy commented on cardano-cli/src/Cardano/CLI/Shelley/Parsers.hs
> +      -- TODO CIP-1694 add --all-active-actions flag when ledger support is available
TODO

2023-05-26 06:32 UTC, newhoggy commented on cardano-cli/test/cardano-cli-golden/files/golden/help.cli
> +            ( --stake-pool-verification-key STRING
Removed!

2023-05-26 06:33 UTC, newhoggy commented on cardano-cli/test/cardano-cli-golden/files/golden/help.cli
> +Usage: cardano-cli governance committee issue-op-cert
Removed!

2023-05-26 06:33 UTC, newhoggy commented on cardano-cli/test/cardano-cli-golden/files/golden/help.cli
> +            ( --stake-verification-key STRING
Removed!

2023-05-26 06:33 UTC, newhoggy commented on cardano-cli/test/cardano-cli-golden/files/golden/help.cli
> +  Create a key pair for a CCM VRF operational key
Removed!

2023-05-26 06:36 UTC, newhoggy commented on cardano-cli/test/cardano-cli-golden/files/golden/help/stake-address.cli
Moved to stage-2

2023-05-26 06:36 UTC, newhoggy commented on cardano-cli/src/Cardano/CLI/Shelley/Commands.hs
> +  | CcNewCounter
Removed!

2023-05-26 06:37 UTC, newhoggy commented on cardano-cli/test/cardano-cli-golden/files/golden/help/governance_vote_view.cli
Left a TODO here https://github.com/input-output-hk/cardano-api/pull/14#discussion_r1206293686

2023-05-26 06:37 UTC, newhoggy commented on cardano-cli/test/cardano-cli-golden/files/golden/help/governance_action_query.cli
Left a TODO here: https://github.com/input-output-hk/cardano-api/pull/14#discussion_r1206293686

2023-05-26 06:38 UTC, newhoggy commented on cardano-cli/test/cardano-cli-golden/files/golden/help.cli
> +Usage: cardano-cli governance committee register-hot-key
@CarlosLopezDeLara can you confirm as well?

2023-06-06 03:16 UTC, newhoggy commented on cardano-cli/test/cardano-cli-golden/files/golden/help/governance_committee_unregister-hot-key.cli
Done!

2023-06-06 07:58 UTC, closed without merging