Add `yq` and `gh`
input-output-hk/cardano-api pull request #145
Opened 2023-07-27 13:24 UTC by yvan-sraka

# Changelog

```yaml
- description: add `yq` and `gh` to developer shell
- compatibility: no-api-changes
- type: maintenance
```

# Context

@newhoggy asked for these tools to be added to the project developer shell (`nix develop`):

- https://github.com/cli/cli
- https://github.com/mikefarah/yq

# Checklist

- [x] Commit sequence broadly makes sense and commits have useful messages
- [x] The change log section in the PR description has been filled in
- [ x New tests are added if needed and existing tests are updated.  These may include:
  - golden tests
  - property tests
  - roundtrip tests
- [x] The version bounds in `.cabal` files are updated
- [ x CI passes. See note on CI.  The following CI checks are required:
  - [x] Code is linted with `hlint`.  See `.github/workflows/check-hlint.yml` to get the `hlint` version
  - [x] Code is formatted with `stylish-haskell`.  See `.github/workflows/stylish-haskell.yml` to get the `stylish-haskell` version
  - [x] Code builds on Linux, MacOS and Windows for `ghc-8.10.7` and `ghc-9.2.7`
- [x] The changelog section in the PR is updated to describe the change
- [x] Self-reviewed the diff

2023-07-27 15:07 UTC, newhoggy approved these changes

2023-07-27 17:50 UTC, carbolymer requested changes
That's wrong yq. We need yq-go here.

2023-07-28 09:08 UTC, carbolymer approved these changes

2023-07-29 03:50 UTC, newhoggy commented
Looks good!

I added `jq` as well.

2023-07-29 03:51 UTC, newhoggy commented
I'm able to run the change log generator scripts using the developer shell now:

```bash
$ ../cardano-dev/scripts/download-prs.sh input-output-hk/cardano-api
Downloading up to 154 PRs
$ ../cardano-dev/scripts/generate-pr-changelogs.sh input-output-hk/cardano-api 84a690d5404e7fd998959d2a5b04fa0ad26bd73f..HEAD
- Add SerialiseAsBech32 instances for committee cold and hot keys
  Remove CommitteeKey as it was redundant
  (feature; breaking)
  [PR 152](https://github.com/input-output-hk/cardano-api/pull/152)

- Clean up constraints on Proposal and Vote instances, add their generators for tests
  (bugfix; compatible)
  [PR 118](https://github.com/input-output-hk/cardano-api/pull/118)
```

2023-07-29 04:08 UTC, merged