More `shelleyBasedEraConstraint` instances
input-output-hk/cardano-api pull request #149
Opened 2023-07-27 23:55 UTC by newhoggy

# Changelog

```yaml
- description: |
    <insert-changelog-description-here>
  # no-api-changes: the API has not changed
  # compatible: the API has changed but is non-breaking
  # breaking: the API has changed in a breaking way
  compatibility: <no-api-changes|compatible|breaking>
  # feature: the change implements a new feature in the API
  # bugfix: the change fixes a bug in the API
  # test: the change fixes modifies tests
  # maintenance: the change involves something other than the API
  # If more than one is applicable, it may be put into a list.
  type: <feature|bugfix|test|maintenance>
```

# Context

Addititional context for the PR goes here.

If the PR fixes a particular issue please provide a
[link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=)
to the issue.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] The change log section in the PR description has been filled in
- [ ] New tests are added if needed and existing tests are updated.  These may include:
  - golden tests
  - property tests
  - roundtrip tests
- [ ] The version bounds in `.cabal` files are updated
- [ ] CI passes. See note on CI.  The following CI checks are required:
  - [ ] Code is linted with `hlint`.  See `.github/workflows/check-hlint.yml` to get the `hlint` version
  - [ ] Code is formatted with `stylish-haskell`.  See `.github/workflows/stylish-haskell.yml` to get the `stylish-haskell` version
  - [ ] Code builds on Linux, MacOS and Windows for `ghc-8.10.7` and `ghc-9.2.7`
- [ ] The changelog section in the PR is updated to describe the change
- [ ] Self-reviewed the diff

# Note on CI
If your PR is from a fork, the necessary CI jobs won't trigger automatically for security reasons.
You will need to get someone with write privileges.  Please contact IOG node developers to do this
for you.

2023-07-28 09:05 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Orphans.hs
> +{-# LANGUAGE UndecidableInstances #-}
Can we avoid this extension? Why it's needed?

2023-07-28 09:07 UTC, carbolymer requested changes
https://github.com/input-output-hk/cardano-api/pull/149/files#r1277303412

2023-07-28 16:12 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Orphans.hs
> +{-# LANGUAGE UndecidableInstances #-}
This is why we need it:

```

internal/Cardano/Api/Orphans.hs:97:10: error:
    • Illegal nested constraint ‘ToJSON (HeaderHash blk)’
      (Use UndecidableInstances to permit this)
    • In the instance declaration for ‘ToJSON (Tip blk)’
   |
97 | instance ToJSON (HeaderHash blk) => ToJSON (Tip blk) where
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Note, the offending instance already exists in `cardano-cli`.  This PR merely moves it here.

2023-07-31 09:10 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Orphans.hs
> +{-# LANGUAGE UndecidableInstances #-}
Your link returns 404 error for me.

2023-07-31 10:17 UTC, carbolymer approved these changes

2023-07-31 13:42 UTC, merged