More feature types and smaller modules
input-output-hk/cardano-api pull request #184
Opened 2023-08-11 14:56 UTC by newhoggy

# Changelog

```yaml
- description: |
    More feature types and smaller modules
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  - improvement    # QoL changes e.g. refactoring
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Additional context for the PR goes here.

If the PR fixes a particular issue please provide a
[link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=)
to the issue.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] The change log section in the PR description has been filled in
- [ ] New tests are added if needed and existing tests are updated.  These may include:
  - golden tests
  - property tests
  - round trip tests
  - integration tests
  See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] The version bounds in `.cabal` files are updated
- [ ] CI passes. See note on CI.  The following CI checks are required:
  - [ ] Code is linted with `hlint`.  See `.github/workflows/check-hlint.yml` to get the `hlint` version
  - [ ] Code is formatted with `stylish-haskell`.  See `.github/workflows/stylish-haskell.yml` to get the `stylish-haskell` version
  - [ ] Code builds on Linux, MacOS and Windows for `ghc-8.10.7` and `ghc-9.2.7`
- [ ] The changelog section in the PR is updated to describe the change
- [ ] Self-reviewed the diff

2023-08-11 20:11 UTC, Jimbo4350 requested changes
Is this a refactoring PR?

2023-08-12 00:11 UTC, newhoggy commented
> Is this a refactoring PR?

A bit of a mix.  Here is a break down by commit name.

New code that matches existing patterns:
* New AlonzoEraOnly feature
* New AlonzoEraOnwards feature
* New BabbageEraOnwards feature
* New ShelleyToAllegraEra feature
* New ShelleyToAlonzoEra feature
* New ShelleyToMaryEra feature
* New ToCardanoEra typeclass

New useful functionality:
* FeatureInEra instances for CardanoEra and ShelleyBasedEra (not yet used)
* New InAnyEra type (not yet used)
* New ProtVer module (Proposing to encapsulate free code into a type with ToJSON/FromJSON instances; not yet used)

Simplification:
* Remove unused language pragmas
* Fine grain imports to improve build parallelism
* Remove unnecessary import of Cardano.Api.ProtocolParameters

Refactoring (moving of code; providing a few extra short functions):
* Move PraosNonce to its own module
* Move type aliases to Cardano.Api.Domain.Common
* Move CostModel to own module
* Move ProtocolParametersError to own module
* Move ExecutionUnitPrices type to its own module
* Move ExecutionUnits to own module

All changes are backwards compatible.

2023-08-13 03:09 UTC, newhoggy commented
Before build optimisation:

```
$ time cabal build all --enable-tests
Build profile: -w ghc-8.10.7 -O1
In order, the following will be built (use -v for more details):
 - cardano-api-8.13.0.0 (lib:internal) (file internal/Cardano/Api/Domain/ProtocolParameters.hs changed)
 - cardano-api-8.13.0.0 (lib) (dependency rebuilt)
 - cardano-api-8.13.0.0 (lib:gen) (dependency rebuilt)
 - cardano-api-gen-8.1.1.1 (lib) (dependency rebuilt)
 - cardano-api-8.13.0.0 (test:cardano-api-test) (dependency rebuilt)
 - cardano-api-8.13.0.0 (test:cardano-api-golden) (dependency rebuilt)
Preprocessing library 'internal' for cardano-api-8.13.0.0..
Building library 'internal' for cardano-api-8.13.0.0..
[87 of 87] Compiling Cardano.Api.Domain.ProtocolParameters ( internal/Cardano/Api/Domain/ProtocolParameters.hs, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/Domain/ProtocolParameters.o, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/Domain/ProtocolParameters.dyn_o )
Preprocessing library for cardano-api-8.13.0.0..
Building library for cardano-api-8.13.0.0..
Preprocessing library 'gen' for cardano-api-8.13.0.0..
Building library 'gen' for cardano-api-8.13.0.0..
Preprocessing library for cardano-api-gen-8.1.1.1..
Building library for cardano-api-gen-8.1.1.1..
Preprocessing test suite 'cardano-api-test' for cardano-api-8.13.0.0..
Preprocessing test suite 'cardano-api-golden' for cardano-api-8.13.0.0..
Building test suite 'cardano-api-golden' for cardano-api-8.13.0.0..
Building test suite 'cardano-api-test' for cardano-api-8.13.0.0..
cabal build all --enable-tests  15.65s user 1.76s system 133% cpu 13.033 total
➜  cardano-api git:(newhoggy/features-for-pparams) ✗ time cabal build all --enable-tests
Build profile: -w ghc-8.10.7 -O1
In order, the following will be built (use -v for more details):
 - cardano-api-8.13.0.0 (lib:internal) (file internal/Cardano/Api/Domain/ProtocolParameters.hs changed)
 - cardano-api-8.13.0.0 (lib) (dependency rebuilt)
 - cardano-api-8.13.0.0 (lib:gen) (dependency rebuilt)
 - cardano-api-gen-8.1.1.1 (lib) (dependency rebuilt)
 - cardano-api-8.13.0.0 (test:cardano-api-test) (dependency rebuilt)
 - cardano-api-8.13.0.0 (test:cardano-api-golden) (dependency rebuilt)
./cardano-api.cabal has been changed. Re-configuring with most recently used
options. If this fails, please run configure manually.
Configuring library 'internal' for cardano-api-8.13.0.0..
Preprocessing library 'internal' for cardano-api-8.13.0.0..
Building library 'internal' for cardano-api-8.13.0.0..
[66 of 87] Compiling Cardano.Api.Domain.ProtocolParametersUpdate ( internal/Cardano/Api/Domain/ProtocolParametersUpdate.hs, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/Domain/ProtocolParametersUpdate.o, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/Domain/ProtocolParametersUpdate.dyn_o )
[67 of 87] Compiling Cardano.Api.Domain.LegacyExecutionUnitPrices ( internal/Cardano/Api/Domain/LegacyExecutionUnitPrices.hs, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/Domain/LegacyExecutionUnitPrices.o, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/Domain/LegacyExecutionUnitPrices.dyn_o )
[68 of 87] Compiling Cardano.Api.Domain.ProtocolParameters ( internal/Cardano/Api/Domain/ProtocolParameters.hs, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/Domain/ProtocolParameters.o, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/Domain/ProtocolParameters.dyn_o )
[69 of 87] Compiling Cardano.Api.ProtocolParameters ( internal/Cardano/Api/ProtocolParameters.hs, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/ProtocolParameters.o, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/ProtocolParameters.dyn_o )
[72 of 87] Compiling Cardano.Api.TxBody ( internal/Cardano/Api/TxBody.hs, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/TxBody.o, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/TxBody.dyn_o )
exprType TYPE: Key
exprType TYPE: Key
./cardano-api.cabal has been changed. Re-configuring with most recently used
options. If this fails, please run configure manually.
Configuring library for cardano-api-8.13.0.0..
Preprocessing library for cardano-api-8.13.0.0..
Building library for cardano-api-8.13.0.0..
[5 of 7] Compiling Cardano.Api      ( src/Cardano/Api.hs, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/build/Cardano/Api.o, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/build/Cardano/Api.dyn_o )
./cardano-api.cabal has been changed. Re-configuring with most recently used
options. If this fails, please run configure manually.
Configuring library 'gen' for cardano-api-8.13.0.0..
Preprocessing library 'gen' for cardano-api-8.13.0.0..
Building library 'gen' for cardano-api-8.13.0.0..
[6 of 7] Compiling Test.Gen.Cardano.Api.Typed ( gen/Test/Gen/Cardano/Api/Typed.hs, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/gen/build/gen/Test/Gen/Cardano/Api/Typed.o, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/gen/build/gen/Test/Gen/Cardano/Api/Typed.dyn_o )
./cardano-api.cabal has been changed. Re-configuring with most recently used
options. If this fails, please run configure manually.
./cardano-api.cabal has been changed. Re-configuring with most recently used
options. If this fails, please run configure manually.
Configuring test suite 'cardano-api-test' for cardano-api-8.13.0.0..
Configuring test suite 'cardano-api-golden' for cardano-api-8.13.0.0..
Preprocessing library for cardano-api-gen-8.1.1.1..
Building library for cardano-api-gen-8.1.1.1..
Preprocessing test suite 'cardano-api-test' for cardano-api-8.13.0.0..
Preprocessing test suite 'cardano-api-golden' for cardano-api-8.13.0.0..
Building test suite 'cardano-api-golden' for cardano-api-8.13.0.0..
Building test suite 'cardano-api-test' for cardano-api-8.13.0.0..
[ 2 of 18] Compiling Test.Cardano.Api.Eras ( test/cardano-api-test/Test/Cardano/Api/Eras.hs, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/t/cardano-api-test/build/cardano-api-test/cardano-api-test-tmp/Test/Cardano/Api/Eras.o )
Linking /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/t/cardano-api-golden/build/cardano-api-golden/cardano-api-golden ...
[ 3 of 18] Compiling Test.Cardano.Api.IO ( test/cardano-api-test/Test/Cardano/Api/IO.hs, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/t/cardano-api-test/build/cardano-api-test/cardano-api-test-tmp/Test/Cardano/Api/IO.o )
[ 4 of 18] Compiling Test.Cardano.Api.Json ( test/cardano-api-test/Test/Cardano/Api/Json.hs, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/t/cardano-api-test/build/cardano-api-test/cardano-api-test-tmp/Test/Cardano/Api/Json.o )
[ 5 of 18] Compiling Test.Cardano.Api.Ledger ( test/cardano-api-test/Test/Cardano/Api/Ledger.hs, /Users/jk [...]

2023-08-13 03:20 UTC, newhoggy commented
Before build optimisation, modifying ExecutionUnits then building looked like this:

 ```
$ time cabal build all --enable-tests
Build profile: -w ghc-8.10.7 -O1
In order, the following will be built (use -v for more details):
 - cardano-api-8.13.0.0 (lib:internal) (file internal/Cardano/Api/Domain/ExecutionUnits.hs changed)
 - cardano-api-8.13.0.0 (lib) (dependency rebuilt)
 - cardano-api-8.13.0.0 (lib:gen) (dependency rebuilt)
 - cardano-api-gen-8.1.1.1 (lib) (dependency rebuilt)
 - cardano-api-8.13.0.0 (test:cardano-api-test) (dependency rebuilt)
 - cardano-api-8.13.0.0 (test:cardano-api-golden) (dependency rebuilt)
Preprocessing library 'internal' for cardano-api-8.13.0.0..
Building library 'internal' for cardano-api-8.13.0.0..
[53 of 85] Compiling Cardano.Api.Domain.ExecutionUnits ( internal/Cardano/Api/Domain/ExecutionUnits.hs, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/Domain/ExecutionUnits.o, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/Domain/ExecutionUnits.dyn_o )
[54 of 85] Compiling Cardano.Api.Script ( internal/Cardano/Api/Script.hs, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/Script.o, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/Script.dyn_o ) [Cardano.Api.Domain.ExecutionUnits changed]
exprType TYPE: Text
exprType TYPE: Text
exprType TYPE: Text
exprType TYPE: Text
exprType TYPE: Text
exprType TYPE: Text
exprType TYPE: Text
exprType TYPE: Text
exprType TYPE: Text
exprType TYPE: Text
exprType TYPE: Text
exprType TYPE: Text
exprType TYPE: Text
exprType TYPE: Text
exprType TYPE: Text
exprType TYPE: Text
exprType TYPE: Text
exprType TYPE: Text
[65 of 85] Compiling Cardano.Api.ProtocolParameters ( internal/Cardano/Api/ProtocolParameters.hs, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/ProtocolParameters.o, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/ProtocolParameters.dyn_o ) [Cardano.Api.Domain.ExecutionUnits changed]
[66 of 85] Compiling Cardano.Api.Governance.Actions.ProposalProcedure ( internal/Cardano/Api/Governance/Actions/ProposalProcedure.hs, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/Governance/Actions/ProposalProcedure.o, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/Governance/Actions/ProposalProcedure.dyn_o ) [Cardano.Api.ProtocolParameters changed]
[67 of 85] Compiling Cardano.Api.GenesisParameters ( internal/Cardano/Api/GenesisParameters.hs, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/GenesisParameters.o, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/GenesisParameters.dyn_o ) [Cardano.Api.ProtocolParameters changed]
[70 of 85] Compiling Cardano.Api.TxBody ( internal/Cardano/Api/TxBody.hs, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/TxBody.o, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/TxBody.dyn_o ) [Cardano.Api.Domain.ExecutionUnits changed]
exprType TYPE: Key
exprType TYPE: Key
[76 of 85] Compiling Cardano.Api.Query ( internal/Cardano/Api/Query.hs, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/Query.o, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/Query.dyn_o ) [Cardano.Api.GenesisParameters changed]
[78 of 85] Compiling Cardano.Api.IPC  ( internal/Cardano/Api/IPC.hs, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/IPC.o, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/IPC.dyn_o ) [Cardano.Api.Query changed]
[79 of 85] Compiling Cardano.Api.LedgerState ( internal/Cardano/Api/LedgerState.hs, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/LedgerState.o, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/LedgerState.dyn_o ) [Cardano.Api.IPC changed]
[80 of 85] Compiling Cardano.Api.IPC.Monad ( internal/Cardano/Api/IPC/Monad.hs, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/IPC/Monad.o, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/IPC/Monad.dyn_o ) [Cardano.Api.IPC changed]
[81 of 85] Compiling Cardano.Api.Query.Expr ( internal/Cardano/Api/Query/Expr.hs, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/Query/Expr.o, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/Query/Expr.dyn_o ) [Cardano.Api.GenesisParameters changed]
[82 of 85] Compiling Cardano.Api.Governance.Poll ( internal/Cardano/Api/Governance/Poll.hs, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/Governance/Poll.o, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/Governance/Poll.dyn_o ) [Cardano.Api.TxBody changed]
[83 of 85] Compiling Cardano.Api.Fees ( internal/Cardano/Api/Fees.hs, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/Fees.o, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/Fees.dyn_o ) [Cardano.Api.Domain.ExecutionUnits changed]
[84 of 85] Compiling Cardano.Api.Convenience.Query ( internal/Cardano/Api/Convenience/Query.hs, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/Convenience/Query.o, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/Convenience/Query.dyn_o ) [Cardano.Api.IPC changed]
[85 of 85] Compiling Cardano.Api.Convenience.Construction ( internal/Cardano/Api/Convenience/Construction.hs, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/Convenience/Construction.o, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/l/internal/build/internal/Cardano/Api/Convenience/Construction.dyn_o ) [Cardano.Api.Fees changed]
Preprocessing library for cardano-api-8.13.0.0..
Building library for cardano-api-8.13.0.0..
[1 of 7] Compiling Cardano.Api      ( src/Cardano/Api.hs, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/build/Cardano/Api.o, /Users/jky/wrk/iohk/cardano-api/dist-newstyle/build/aarch64-osx/ghc-8.10.7/cardano-api-8.13.0.0/build/Cardano/Api.dyn_o ) [Cardano.Api.Conv [...]

2023-08-13 03:45 UTC, newhoggy commented
For full build times, the savings of this PR is much less (`4s` savings out of `5m7`), but then, it's still an improvement and remains a lot of module dependency bottlenecks in the code.

The PR demonstrates that avoiding module dependency bottlenecks help build concurrency and reduces build times, so it is recommended that going forward we prefer smaller modules and more precise dependencies for parts of the code we are working on.

2023-08-14 09:38 UTC, carbolymer approved these changes

2023-08-14 17:36 UTC, Jimbo4350 requested changes
Again, let's not do anymore refactoring PRs until we have a SanchoNet demo. Anything not explicitly working towards that I will block until after we have SanchoNet.

2023-10-04 13:36 UTC, closed without merging