Update cardano-api to a newer cardano-ledger
input-output-hk/cardano-api pull request #227
Opened 2023-09-04 15:47 UTC by coot

# Changelog

```yaml
- description: |
    <insert-changelog-description-here>
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - improvement    # QoL changes e.g. refactoring
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
    - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Make `cardano-api` compatible with a newer ledger input-output-hk/cardano-ledger@9e2f8151e3b9a0dde9faeb29a7dd2456e854427c.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] The change log section in the PR description has been filled in
- [ ] New tests are added if needed and existing tests are updated.  These may include:
  - golden tests
  - property tests
  - round trip tests
  - integration tests
  See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] The version bounds in `.cabal` files are updated
- [ ] CI passes. See note on CI.  The following CI checks are required:
  - [ ] Code is linted with `hlint`.  See `.github/workflows/check-hlint.yml` to get the `hlint` version
  - [ ] Code is formatted with `stylish-haskell`.  See `.github/workflows/stylish-haskell.yml` to get the `stylish-haskell` version
  - [ ] Code builds on Linux, MacOS and Windows for `ghc-8.10.7` and `ghc-9.2.7`
- [ ] The changelog section in the PR is updated to describe the change
- [ ] Self-reviewed the diff

2023-09-04 16:41 UTC, coot commented on cardano-api/internal/Cardano/Api/Convenience/Query.hs
> +      drepCreds  = undefined :: Set DRepCredential -- TODO: should `drepCreds` come from certs?
@lehins were should `drepCreds` come from. They are passed to the `QueryDRepState` which returns [drepDeposit](https://input-output-hk.github.io/cardano-ledger/cardano-ledger-core/Cardano-Ledger-DRepDistr.html#t:DRepState) from `DRepState`.  The results of `queryStateForBalancedTx` are used to construct a transaction with `makeTransactionBodyAutoBalance` which is also update in this commit.

2023-09-04 16:52 UTC, coot commented on cardano-api/internal/Cardano/Api/Convenience/Query.hs
> +      drepCreds  = undefined :: Set DRepCredential -- TODO: should `drepCreds` come from certs?
`ConwayTxCert` contains [`ConwayRegDRep`](https://input-output-hk.github.io/cardano-ledger/cardano-ledger-conway/Cardano-Ledger-Conway-TxCert.html#t:ConwayGovCert), is this the right source?

2023-09-04 18:36 UTC, lehins commented on cardano-api/internal/Cardano/Api/Convenience/Query.hs
> +      drepCreds  = undefined :: Set DRepCredential -- TODO: should `drepCreds` come from certs?
Yes, you got it. `QueryDRepState` is the right query, except you need to look through the DRep unregistration certificates, instead of registration. Because the `drepCreds` need to be a `Map DRepCredential Coin`, where coin is the deposit that was left upon registration and will be refunded in this transaction that is being built. So here is the value that you need:
https://github.com/input-output-hk/cardano-ledger/blob/453d19da239d0eb123a98aabac2f74f5bfdb41f7/libs/cardano-ledger-core/src/Cardano/Ledger/DRepDistr.hs#L54

And this is the pattern synonym for the certificates that you need to collect from the transaction: https://github.com/input-output-hk/cardano-ledger/blob/453d19da239d0eb123a98aabac2f74f5bfdb41f7/libs/cardano-ledger-api/src/Cardano/Ledger/Api/Tx/Cert.hs#L60

2023-09-04 22:04 UTC, coot commented on cardano-api/internal/Cardano/Api/Convenience/Query.hs
> +      drepCreds  = undefined :: Set DRepCredential -- TODO: should `drepCreds` come from certs?
Thanks, here it is:

* [queryStateForBalancedTx](https://github.com/input-output-hk/cardano-api/blob/coot/cardano-ledger-conway-1.8/cardano-api/internal/Cardano/Api/Convenience/Query.hs?plain=1#L97)
* [filterUnRegDRepCreds](https://github.com/input-output-hk/cardano-api/blob/coot/cardano-ledger-conway-1.8/cardano-api/internal/Cardano/Api/Certificate.hs#L720-L726)

2023-09-05 09:02 UTC, lehins commented on cardano-api/internal/Cardano/Api/Convenience/Query.hs
> +      drepCreds  = undefined :: Set DRepCredential -- TODO: should `drepCreds` come from certs?
Perfect :+1:

2023-09-08 12:07 UTC, Jimbo4350 requested changes

2023-09-08 12:07 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Address.hs
> +newtype DRepCredential = DRepCredential { unDRepCredential :: Shelley.Credential 'Shelley.DRepRole StandardCrypto }
Let's use the edger type directly

2023-09-08 12:07 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Convenience/Construction.hs
> +  -> Map.Map DRepCredential Lovelace
@newhoggy @carbolymer what do you think about a single sum type to handle stake and drep credentials?

2023-09-08 12:10 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Convenience/Construction.hs
> +  -> Map.Map DRepCredential Lovelace
I think if the ledger types are distinct, I prefer to keep them separate and if they are not, I prefer to new the ledger type itself or a `newtype` wrapper over it.

2023-09-08 12:57 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Convenience/Construction.hs
> +  -> Map.Map DRepCredential Lovelace
Isn't that what ledger `Credential` type already is?

2023-09-08 13:23 UTC, coot commented on cardano-api/internal/Cardano/Api/Address.hs
> +newtype DRepCredential = DRepCredential { unDRepCredential :: Shelley.Credential 'Shelley.DRepRole StandardCrypto }
Note that newtype wrappers can help you in the future protect upstream from breaking ledger changes.

2023-09-08 15:18 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Address.hs
> +newtype DRepCredential = DRepCredential { unDRepCredential :: Shelley.Credential 'Shelley.DRepRole StandardCrypto }
I want to as much as possible not maintain any ledger related types in cardano-api.

2023-09-11 08:29 UTC, coot commented on cardano-api/internal/Cardano/Api/Address.hs
> +newtype DRepCredential = DRepCredential { unDRepCredential :: Shelley.Credential 'Shelley.DRepRole StandardCrypto }
Resolved.

2023-09-12 11:24 UTC, coot commented on cardano-api/internal/Cardano/Api/Address.hs
> +newtype DRepCredential = DRepCredential { unDRepCredential :: Shelley.Credential 'Shelley.DRepRole StandardCrypto }
Note that `newtypes` help with two things:

* protect upstream libraries
* hide unnecessary details (in this case not exposing two type parameters which are irrelevant for upstream users)

They also can simplify maintnance, since they limit what needs to changed in the provided API.

2023-09-12 11:33 UTC, newhoggy approved these changes

2023-09-12 12:25 UTC, merged