Delete TxFeesExplicitInEra` and `TxFeesImplicitInEra`
input-output-hk/cardano-api pull request #244
Opened 2023-09-14 07:05 UTC by newhoggy

# Changelog

```yaml
- description: |
    Delete TxFeesExplicitInEra` and `TxFeesImplicitInEra`
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  - improvement    # QoL changes e.g. refactoring
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Additional context for the PR goes here.

If the PR fixes a particular issue please provide a
[link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=)
to the issue.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] The change log section in the PR description has been filled in
- [ ] New tests are added if needed and existing tests are updated.  These may include:
  - golden tests
  - property tests
  - round trip tests
  - integration tests
  See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] The version bounds in `.cabal` files are updated
- [ ] CI passes. See note on CI.  The following CI checks are required:
  - [ ] Code is linted with `hlint`.  See `.github/workflows/check-hlint.yml` to get the `hlint` version
  - [ ] Code is formatted with `stylish-haskell`.  See `.github/workflows/stylish-haskell.yml` to get the `stylish-haskell` version
  - [ ] Code builds on Linux, MacOS and Windows for `ghc-8.10.7` and `ghc-9.2.7`
- [ ] The changelog section in the PR is updated to describe the change
- [ ] Self-reviewed the diff

2023-09-14 07:28 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Fees.hs
> +                 txFee  = TxFeeExplicit sbe $ Lovelace (2^(32 :: Integer) - 1),
We can just provide `sbe` as the witness instead of make up another one.

2023-09-14 07:28 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/TxBody.hs
> +    (cardanoEra @era)
We can using casing functions now, avoiding the need to enumerate all eras.

2023-09-14 07:29 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/TxBody.hs
> +    $ fromShelleyLovelace $ body ^. L.feeTxBodyL
We can use `sbe` here as well and not have to enumerate all eras and use constraints functions to summon constraints.

2023-09-14 13:58 UTC, Jimbo4350 requested changes
No, I disagree. It's going to be confusing having the era related code in different name spaces. The era itself isn't a feature, it represents a boundary IMO.

2023-09-14 14:03 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Fees.hs
> +                 txFee  = TxFeeExplicit sbe $ Lovelace (2^(32 :: Integer) - 1),
The explicit/implicit refactoring looks good. I would approve it in a separate PR.

2023-09-15 06:42 UTC, newhoggy commented
> No, I disagree. The era itself isn't a feature, it represents a boundary between feature sets IMO.

Maybe `Feature` is not the right word?  Stuff like `ShelleyToBabbageEra` and `ConwayEraOnwards` are more like era selectors for other things that are features.  `BabbageEraOnly` has that kind of shape.

2023-09-15 09:20 UTC, carbolymer approved these changes

2023-09-15 11:53 UTC, Jimbo4350 commented
> > No, I disagree. The era itself isn't a feature, it represents a boundary between feature sets IMO.
> 
> Maybe `Feature` is not the right word? Stuff like `ShelleyToBabbageEra` and `ConwayEraOnwards` are more like era selectors for other things that are features. `BabbageEraOnly` has that kind of shape.
> 
> If we had another word to replace `Feature` that fit, I think it would work.

I don't think it's worth the churn. However the fee refactoring is good.

2023-09-20 22:07 UTC, newhoggy commented
`FeatureInEra` has been renamed to `Eon` so the misnaming doesn't apply anymore.

2023-09-20 22:34 UTC, merged