Simplify `createTransactionBody`
input-output-hk/cardano-api pull request #333
Opened 2023-10-20 13:21 UTC by newhoggy

# Changelog

```yaml
- description: |
    Simplify `createTransactionBody`
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  - improvement    # QoL changes e.g. refactoring
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Includes commits from https://github.com/input-output-hk/cardano-api/pull/333 so review that first.

# How to trust this PR

Highlight important bits of the PR that will make the review faster. If there are commands the reviewer can run to observe the new behavior, describe them.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] Self-reviewed the diff

2023-10-20 13:24 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/TxBody.hs
> +createTransactionBody sbe bc =
The focus of this PR is to simplify this function.

The earlier version of this code case matches on `sbe` and handles each era therein separately resulting in a lot of duplicate code.

The new version of this function instead eliminates the large case expression and instead uses eons allow each feature to determine for themselves if they need to set their values into the TxBody.

2023-10-21 04:19 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/TxBody.hs
> +        sbe
With this refactoring we can deal with each tx body feature in isolation without duplication.

This can be simplified further in a future PR.

2023-10-21 04:20 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/TxBody.hs
> +            & modifyWith setTotalCollateral
`modityWith` shouldn't be necessary but `ghc`'s type inference isn't quite there.

2023-10-21 04:21 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/TxBody.hs
> +    let aOn = AllegraEraOnwardsBabbage
This is just temporary because we need a witness.  A future PR will get rid of this.

2023-10-21 04:22 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/TxBody.hs
> +            & L.invalidHereAfterTxBodyL sbe .~ convValidityUpperBound sbe txValidityUpperBound
These lenses take witnesses instead of constraints.  This can be used in future to simplify code.

2023-10-21 04:23 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/TxBody.hs
> -       ShelleyBasedEraShelley -> do
One of the goals of this PR is to eliminate to need to case match on the era and handle each era separately.  Doing away with this case expression vastly reduces code duplication and the potential for error.

2023-10-23 10:21 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Utils.hs
> +-- | Aids type inference.  Use this function to ensure the value is a function
I think I don't understand that. There's no modification happening in this function, so the comment and naming is misleading.

2023-10-23 10:24 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/TxBody.hs
> +            & modifyWith setCollateralReturn
Invocations of `modifyWith` are not changing the value, so the before and after versions of the code have different meaning.

2023-10-23 10:24 UTC, carbolymer requested changes
https://github.com/input-output-hk/cardano-api/pull/333/files#r1368451851

2023-10-23 12:48 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Utils.hs
> +-- | Aids type inference.  Use this function to ensure the value is a function
The function doesn't do anything and should behave the same as `id`.  The only reason it is used at all is to help with type-inference.  You can remove the function calls and observe that type-inference fails.

2023-10-25 06:01 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/TxBody.hs
> +        sbe
Why do you need `>>=` here? Why not:
```suggestion
let setMint =
      caseShelleyToAllegraOrMaryEraOnwards
        (const $ id)
        (const $ L.mintTxBodyL .~ convMintValue apiMintValue)
        sbe
```

2023-10-25 06:02 UTC, carbolymer approved these changes

2023-10-27 07:28 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/TxBody.hs
> +        sbe
This is mostly to make all of the units of code have the same shape rather than have some unit use `let` and others use `<-`.

You are right in that the `>>=` is not needed.

2023-10-29 04:19 UTC, merged