Switch to use lens and eons for txbody construction
input-output-hk/cardano-api pull request #334
Opened 2023-10-21 04:12 UTC by newhoggy

# Changelog

```yaml
- description: |
    Switch to use lens and eons for txbody construction
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  - improvement    # QoL changes e.g. refactoring
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Additional context for the PR goes here. If the PR fixes a particular issue please provide a [link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=) to the issue.

# How to trust this PR

Highlight important bits of the PR that will make the review faster. If there are commands the reviewer can run to observe the new behavior, describe them.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] Self-reviewed the diff

2023-10-21 07:23 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/TxBody.hs
> +      (A.updateTxBodyL w .~) <$> convTxUpdateProposal sbe (txUpdateProposal bc)
Because the lenses we use take an eon we can use `forShelleyBasedEraInEon` and not care about what eons the field is valid for.

This is one of the advantages of using eons over constraints.

In a future era the ledger ends support for a field, then only the lens need change.  This code will not need to change at all, reducing the blast radius of ledger changes.

2023-10-21 07:24 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Ledger/Lens.hs
> +updateTxBodyL w = shelleyToBabbageEraConstraints w $ txBodyL . L.updateTxBodyL
Notice that `updateBodyL` takes a `ShelleyToBabbageEra` eon and internally summons the necessary constraint so the caller doesn't have to.

2023-10-23 10:25 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/TxBody.hs
> +            & modifyWith setCollateralInputs
https://github.com/input-output-hk/cardano-api/pull/333/files#r1368451851

2023-10-23 10:25 UTC, carbolymer requested changes
This includes #333, so I have the same remark here https://github.com/input-output-hk/cardano-api/pull/333/files#r1368451851

2023-10-23 13:18 UTC, Jimbo4350 requested changes

2023-10-23 13:18 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Ledger/Lens.hs
> +invalidBeforeTxBodyL :: AllegraEraOnwards era -> Lens' (TxBody era) (Maybe SlotNo)
Why are we making this change that depends more on the eons when we intend to remove them?

2023-10-23 14:01 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Ledger/Lens.hs
> +invalidBeforeTxBodyL :: AllegraEraOnwards era -> Lens' (TxBody era) (Maybe SlotNo)
We hadn't yet planned how much we're going to trim which may affect what we keep and what we don't.  We should have that discussion.

2023-10-25 07:23 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/TxBody.hs
> +      (A.updateTxBodyL w .~) <$> convTxUpdateProposal sbe (txUpdateProposal bc)
Tbh I'd prefer using:
```haskell
setUpdateProposal <- forEraInEon (cardanoEra @era) (pure id) $ \w ->
...
```
Removes the need for maintaining multiple specialized functions for each eon.

2023-10-25 07:44 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/TxBody.hs
> +    setInvalidBefore <- forShelleyBasedEraInEon sbe (pure id) $ \w ->
There's a lot of repetition of functions like:
```haskell
forShelleyBasedEraInEon sbe (pure id) $ \w -> ...
```

It feels that we could use a `Monoid (Ap f (Endo a))` here. For example:

```haskell
whenShelleyBasedEraInEon :: ()
  => Eon eon
  => Monoid a
  => ShelleyBasedEra era
  -> (eon era -> a)
  -> a
whenShelleyBasedEraInEon sbe f = forShelleyBasedEraInEon sbe mempty f
```
then 

```haskell
let setMint = whenShelleyBasedEraInEon sbe $ Endo $ \w ->
  A.mintTxBodyL w .~ convMintValue apiMintValue
```
or
```haskell
  setUpdateProposal <- getAp <$> whenShelleyBasedEraInEon sbe $ Ap $ \w ->
    (Endo $ A.updateTxBodyL w .~) <$> convTxUpdateProposal sbe (txUpdateProposal bc)
```
and then when constructing the txbody use `<>` instead of `&`.

What do you think?

2023-10-25 07:50 UTC, carbolymer approved these changes

2023-10-30 10:08 UTC, smelc commented on cardano-api/internal/Cardano/Api/Eon/AlonzoEraOnwards.hs
> +  , L.AlonzoEraTxOut (ShelleyLedgerEra era)
This seems unnecessary, this constraint is already there, on the previous line.

2023-10-30 11:07 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/TxBody.hs
> +    setInvalidBefore <- forShelleyBasedEraInEon sbe (pure id) $ \w ->
Possible follow up step.

2023-10-30 11:14 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Eon/AlonzoEraOnwards.hs
> +  , L.AlonzoEraTxOut (ShelleyLedgerEra era)
Yep.  You are right!

2023-10-30 11:16 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Eon/AlonzoEraOnwards.hs
> +  , L.AlonzoEraTxOut (ShelleyLedgerEra era)
Fixed!

2023-10-30 11:18 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/TxBody.hs
> +      (A.updateTxBodyL w .~) <$> convTxUpdateProposal sbe (txUpdateProposal bc)
I wasn't intending to create one for each eon.  Just CardanoEra and ShelleyBasedEra.  We can promote sbe to era as well.

2023-10-30 11:21 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/TxBody.hs
> +      (A.updateTxBodyL w .~) <$> convTxUpdateProposal sbe (txUpdateProposal bc)
How does it look now?

2023-10-30 11:55 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/TxBody.hs
> +    setInvalidBefore <- forShelleyBasedEraInEon sbe (pure id) $ \w ->
I pushed the suggested change with some slight changes.

2023-10-31 11:00 UTC, merged