foldBlocks update
input-output-hk/cardano-api pull request #350
Opened 2023-10-31 19:41 UTC by Jimbo4350

Add Show instance for FoldBlocksError
Additional show instances
Added error for when tips are equal
Add more debuging information in error message
Add termination bool
Finish when termination bool == True
Use atomicWriteIORef

# Changelog

```yaml
- description: |
    <insert-changelog-description-here>
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - improvement    # QoL changes e.g. refactoring
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Additional context for the PR goes here. If the PR fixes a particular issue please provide a [link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=) to the issue.

# How to trust this PR

Highlight important bits of the PR that will make the review faster. If there are commands the reviewer can run to observe the new behavior, describe them.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] Self-reviewed the diff

2023-11-02 10:51 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/LedgerState.hs
> +-- Type that lets us decide whether to continue or stop
```suggestion
-- | Type that lets us decide whether to continue or stop
```

2023-11-02 11:06 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/LedgerState.hs
> +                                                                           , "newServerTip: " <> show newServerTip
this indentation looks off in github

2023-11-02 11:35 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/LedgerState.hs
> +                      -- concatenation of all the ledger events in the accumulation function.
This comment isn't super clear to me. `TChan` can't be used as a drop-in replacement for `stateIORef :: IORef a` here, as how exactly accumulation is done is dictated by `accumulate` function. This means, that `newState` returned by `accumulate` doesn't have to be a FIFO stream (which is a `TChan` is), but can have any shape.
Can you clarify what do you mean here?

2023-11-02 11:49 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/LedgerState.hs
> +                      foldStatuses <- forM knownLedgerStates' $ \(_, (ledgerState, ledgerEvents), currBlockMay) -> case currBlockMay of
If we're only interested in the first occurrence of a `FoldStatus` (this is what `foldDecision` does), this should be a set instead of a sequence. This way we would avoid accumulating all the unnecessary `foldStatus`es. `foldM` can be used here.

2023-11-02 11:54 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/LedgerState.hs
> +                          clientIdle_DoneNwithMaybeError n ioRefErr
I'm not sure how soon this gets logged/written somewhere, but it may be worth enforcing strictness here
```suggestion
                          deepseq ioRefErr $ clientIdle_DoneNwithMaybeError n ioRefErr
```

2023-11-02 11:56 UTC, carbolymer requested changes
https://github.com/input-output-hk/cardano-api/pull/350/files#r1379986767

2023-11-02 14:21 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/LedgerState.hs
> +                          clientIdle_DoneNwithMaybeError n ioRefErr
This is left over from my debugging. I'll remove it.

2023-11-02 15:37 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/LedgerState.hs
> +                      foldStatuses <- forM knownLedgerStates' $ \(_, (ledgerState, ledgerEvents), currBlockMay) -> case currBlockMay of
Ok. It's that the current implementation does only check for the presence of an element in the list.

2023-11-03 13:20 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/LedgerState.hs
> +                      -- concatenation of all the ledger events in the accumulation function.
We discussed on slack but I will remove the comment regarding the `TChan`. I'll make a PR in the near future to address this.

2023-11-03 13:25 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/LedgerState.hs
> +                      foldStatuses <- forM knownLedgerStates' $ \(_, (ledgerState, ledgerEvents), currBlockMay) -> case currBlockMay of
The plan is to recurse on `knownLedgerStates'` instead and exit (or continue) depending on the value of `FoldStatus`. This will be in a follow up PR so I could keep the diff small here.

2023-11-03 13:26 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/LedgerState.hs
> +                                                                           , "newServerTip: " <> show newServerTip
Fixed :+1:

2023-11-03 14:02 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/LedgerState.hs
> +                          clientIdle_DoneNwithMaybeError n ioRefErr
So this would be ideal but I would need to derive `NFData` instances for types in consensus that currently don't exist.

2023-11-03 14:07 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/LedgerState.hs
> +  | DebugError String
```suggestion
  | DebugError !String
```

2023-11-03 15:00 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/LedgerState.hs
> +                      foldStatuses <- forM knownLedgerStates' $ \(_, (ledgerState, ledgerEvents), currBlockMay) -> case currBlockMay of
https://github.com/input-output-hk/cardano-api/pull/353/commits/f73699815056a29e3c6a7a9f33079e1df96bf1ec

2023-11-03 16:32 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/LedgerState.hs
> +                          clientIdle_DoneNwithMaybeError n ioRefErr
```suggestion
                          let !ioRefErr = DebugError
                                              $ unlines [ "newClientTip: " <> show newClientTip
                                                        , "newServerTip: " <> show newServerTip
                                                        , "newLedgerState: " <> show (snd newLedgerState)
                                                        , "knownLedgerStates: " <> show (extractHistory knownLedgerStates)
                                                        , "committedStates: " <> show (extractHistory committedStates)
                                                        , "numberOfRequestsInFlight: " <> show n
                                                        , "k: " <> show (envSecurityParam env)
                                                        , "Current IORef State: " <> show currentIORefState
                                                        ]
                          clientIdle_DoneNwithMaybeError n (Just ioRefErr)
```

2023-11-03 16:34 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/LedgerState.hs
> +                          clientIdle_DoneNwithMaybeError n ioRefErr
Right. I guess we can get around using NFData with `BangPatterns`:
1. Make `DebugError` constructor field strict
2. use `let !ioRefError = DebugError`
3. wrap `ioRefErr` in `Just` when calling `clientIdle_DoneNwithMaybeError`, because `Maybe` is lazy

2023-11-06 09:14 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/LedgerState.hs
> +                          let ioRefErr = DebugError . force
```suggestion
                          let !ioRefErr = DebugError . force
```
otherwise `ioError` will still be a thunk here, until we evaluate it somewhere

2023-11-06 13:27 UTC, carbolymer approved these changes

2023-11-06 14:46 UTC, merged