Delete `ByronToAllegraEra` eon
input-output-hk/cardano-api pull request #356
Opened 2023-11-06 13:15 UTC by newhoggy

# Changelog

```yaml
- description: |
    Delete `ByronToAllegraEra` eon
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  # - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - improvement    # QoL changes e.g. refactoring
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

The reason we needed `ByronToAllegraEra` eon was because we had code that wanted to treat Byron era and subsequent eras the same way.  If we give Byron era it's own constructor, the need goes away.

# How to trust this PR

Highlight important bits of the PR that will make the review faster. If there are commands the reviewer can run to observe the new behavior, describe them.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] Self-reviewed the diff

2023-11-06 13:16 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/TxBody.hs
> -  TxOutAdaOnly :: ByronToAllegraEra era -> Lovelace -> TxOutValue era
We split this constructor to avoid needing an extra eon.

2023-11-06 13:39 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/TxBody.hs
> -  TxOutAdaOnly :: ByronToAllegraEra era -> Lovelace -> TxOutValue era
Not sure that's worth it. We're removing one eon, but the additional constructor is not handling any special behaviour and makes code a bit confusing.

2023-11-06 13:39 UTC, carbolymer reviewed
https://github.com/input-output-hk/cardano-api/pull/356/files#r1383315760
I'm not sure if this change is beneficial.

2023-11-06 13:57 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/TxBody.hs
> -  TxOutAdaOnly :: ByronToAllegraEra era -> Lovelace -> TxOutValue era
Yeah, there's a tradeoff.

2023-11-06 14:12 UTC, Jimbo4350 requested changes
Let's refrain from more changes to the api concerning eons. We need to decide a way forward.

2023-11-08 09:28 UTC, closed without merging

2023-11-08 09:28 UTC, newhoggy commented
Closing for the moment.  Revisit later.