Use ledger presentation of multi-asset values
input-output-hk/cardano-api pull request #360
Opened 2023-11-08 14:39 UTC by newhoggy

# Changelog

```yaml
- description: |
    Use ledger presentation of multi-asset values
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  # - improvement    # QoL changes e.g. refactoring
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

Additional context for the PR goes here. If the PR fixes a particular issue please provide a [link](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword=) to the issue.

# How to trust this PR

Highlight important bits of the PR that will make the review faster. If there are commands the reviewer can run to observe the new behavior, describe them.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] Self-reviewed the diff

2023-11-08 14:40 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Eon/ByronToAllegraEra.hs
> -module Cardano.Api.Eon.ByronToAllegraEra
This PR deletes `ByronToAllegraEra`

2023-11-08 14:41 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Eras/Case.hs
> -  ConwayEra  -> r MaryEraOnwardsConway
Deletes a case function because we don't need it anymore.

2023-11-08 14:48 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/TxBody.hs
> +          & L.referenceScriptTxOutL .~ refScriptToShelleyScript cEra refScript
The `L.mkBasicTxOut (toShelleyAddr addr) value` is repeated `6` times.  Potential to simplify.

2023-11-08 14:49 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/TxBody.hs
> +    -> TxOutValue era
This definition has two constructors like before, the main difference is that all Shelley eras are now treated the same and only Byron is different.  This is as it should be because the ledger treats Byron as legacy so it doesn't even have lens support.

2023-11-08 14:50 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/TxBody.hs
> +    TxOutValueShelleyBased  sbe v -> coinToLovelace $ v ^. A.adaAssetL sbe
Example of where we use `adaAssetL` to access the ADA value.

2023-11-08 14:51 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/TxBody.hs
> +    cEra = shelleyBasedToCardanoEra sbe
Opportunity to simplify because `L.mkBasicTxOut (toShelleyAddr addr) value` is repeated.  This wasn't the case previously.

2023-11-08 14:52 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Value.hs
> +coinToLovelace (Shelley.Coin ll) = Lovelace ll
We could delete `Lovelace` and use the `Coin` ledger type directly to avoid conversions.

2023-11-08 14:53 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Value.hs
> +    sbe
These conversions were functions were introduced to convert between `Value` and `L.Value ledgerera`.  `Value` could actually be deleted if we use the ledger type directly everywhere and then these conversion functions go away.

2023-11-08 14:55 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/TxBody.hs
> +  let txOutValue = TxOutValueShelleyBased sbe $ ledgerTxOut ^. A.valueTxOutL sbe
If we use the ledger types directly we no longer have to convert to `cardano-api`'s representation so this simplifies considerably.

2023-11-08 15:03 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/TxBody.hs
> +          & L.dataHashTxOutL .~ toAlonzoTxOutDataHash' txoutdata
`dataHashTxOutL` is only used in Alonzo?  Why?  Can we delete it?

2023-11-08 15:15 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/TxBody.hs
> -    & L.dataHashTxOutL .~ toAlonzoTxOutDataHash txoutdata
This appears to be Alonzo only.  Deleting this can simplify the code a lot.

2023-11-09 06:40 UTC, newhoggy commented on cardano-api/cardano-api.cabal
> +  reexported-modules:   Cardano.Api.Ledger.Lens
New export so we can use eon enabled from the CLI and from tests.

2023-11-09 06:54 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Fees.hs
> +    let change = mconcat [incoming, minted, negateLedgerValue sbe outgoing]
In the above code this differs from the previous code in that we also add all the Ada/Lovelace as well, but that doesn't change the behaviour because with throw away that value anyway with the computation of `changeWithMaxLovelace`.

2023-11-09 06:56 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/TxBody.hs
> -fromAlonzoTxOutDataHash s (SJust dh)   = TxOutDatumHash s (ScriptDataHash dh)
A bunch of alonzo specific code disappears because we remove the feature that only worked in Alonzo.

2023-11-09 06:57 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/TxBody.hs
> -    | otherwise                         -> TxOutDatumHash w (ScriptDataHash dh)
A bunch of alonzo specific code disappears because we remove the feature that only worked in Alonzo and choose to no longer support.

2023-11-09 06:58 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/TxBody.hs
> -       & L.datumTxOutL .~ toBabbageTxOutDatum' txoutdata
A bunch of alonzo specific code disappears because we remove the feature that only worked in Alonzo and choose to no longer support.

2023-11-09 07:00 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Fees.hs
> -            txbody
Because the lens adapter makes the ADA asset interface consistent across all of `ShelleyBasedEra` we no longer need to case on the eon to implement `evaluateTransactionBalance`.

2023-11-09 07:02 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/TxBody.hs
> -      addressInEra = shelleyBasedEraConstraints sbe $ fromShelleyAddr sbe $ ledgerTxOut ^. L.addrTxOutL
More simplifications because the eon-enabled lens adapter makes ADA Asset appear uniform across all of `ShelleyBasedEra`.

2023-11-09 07:03 UTC, newhoggy commented on cardano-api/cardano-api.cabal
> +                      , groups
We import `groups` because ledger implements `Group` for multi-asset values which we can use to negative the entire `L.Value ledgerera`.

2023-11-09 12:15 UTC, carbolymer approved these changes

2023-11-09 13:51 UTC, Jimbo4350 requested changes

2023-11-09 13:51 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Ledger/Lens.hs
> +    sbe
We need to move this lens to `cardano-ledger` in a follow up PR.

2023-11-09 13:51 UTC, Jimbo4350 commented on cardano-api/cardano-api.cabal
> +  reexported-modules:   Cardano.Api.Ledger.Lens
Why not just expose it?

2023-11-09 13:51 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Fees.hs
> +    $ TxOutValueShelleyBased sbe
:+1:

2023-11-09 13:51 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Fees.hs
> +    let outgoingNonAda = mconcat [v | (TxOut _ (TxOutValueShelleyBased _ v) _ _) <- txOuts txbodycontent]
Where has the `isNotAda` filter gone?

2023-11-09 13:51 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Ledger/Lens.hs
> +mkAdaValue :: ShelleyBasedEra era -> L.Coin -> L.Value (ShelleyLedgerEra era)
Another function that should live in the ledger

2023-11-09 13:51 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Value.hs
> +coinToLovelace (Shelley.Coin ll) = Lovelace ll
We should in another PR.

2023-11-09 13:51 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/TxBody.hs
> -          & L.dataHashTxOutL .~ toAlonzoTxOutDataHash txoutdata
```
     -- | A transaction output that only specifies the hash of the datum, but
     -- not the full datum value.
     --
     TxOutDatumHash   :: AlonzoEraOnwards era
                      -> Hash ScriptData
                      -> TxOutDatum ctx era
```
So this depends on the incoming `TxOut`.

2023-11-09 13:51 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/TxBody.hs
> -fromAlonzoTxOutDataHash s (SJust dh)   = TxOutDatumHash s (ScriptDataHash dh)
datum hashes weren't deprecated. See in ledger: `instance Crypto c => AlonzoEraTxOut (BabbageEra c) where`

2023-11-09 14:03 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Fees.hs
> +    let outgoingNonAda = mconcat [v | (TxOut _ (TxOutValueShelleyBased _ v) _ _) <- txOuts txbodycontent]
In the old code, `isNotAda` removes the ADA asset, which is equivalent to setting the ADA asset value to zero.  Later the ADA asset value is set by way of addition so the zero value is necessary:

> lovelaceToValue (Lovelace (2^(64 :: Integer)) - 1) <> nonAdaChange

The new code doesn't both to set it to zero because instead of adding `nonAdaChange` to the ADA asset value we overwrite it with `nonAdaChange` instead:

> `change & A.adaAssetL sbe .~ lovelaceToCoin maxLovelaceChange`

2023-11-09 14:21 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/TxBody.hs
> -
The code above gets the hash and the code below also gets the hash as a `Datum`.

2023-11-09 15:05 UTC, newhoggy commented on cardano-api/cardano-api.cabal
> +  reexported-modules:   Cardano.Api.Ledger.Lens
The code needs to live in the `internal` component because code in `internal` uses it.  this doesn't apply to the other modules because those are never imported by code in `internal`.

2023-11-09 15:39 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Fees.hs
> +    let outgoing = mconcat [v | (TxOut _ (TxOutValueShelleyBased _ v) _ _) <- txOuts txbodycontent]
This now includes ada

2023-11-09 15:47 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Ledger/Lens.hs
>    , L.invalidBeforeL
We need a clear distinction between ledger and cardano-api. We are mixing lenses here.

2023-11-09 16:04 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/TxBody.hs
> +    -> TxOutValue era
The `TxOutValueByron` constructor will eventually be removed because:
```
makeByronTransactionBody :: ()
  => ByronEraOnly era
  -> TxBodyContent BuildTx era
  -> Either TxBodyError (TxBody era)
```

We don't need `TxBodyContent BuildTx Era` to construct a Byron tx. We are only interested in inputs, outputs and update proposals and we can parameterize `makeByronTransactionBody` as such.

2023-11-10 00:54 UTC, merged