Merge `ShelleyLedgerEra` and `CardanoLedgerEra` to a single type family `LedgerEra`
input-output-hk/cardano-api pull request #361
Opened 2023-11-09 15:48 UTC by newhoggy

# Changelog

```yaml
- description: |
    Merge `ShelleyLedgerEra` and `CardanoLedgerEra` to a single type family `LedgerEra`
# uncomment types applicable to the change:
  type:
  # - feature        # introduces a new feature
  - breaking       # the API has changed in a breaking way
  # - compatible     # the API has changed but is non-breaking
  # - optimisation   # measurable performance improvements
  - improvement    # QoL changes e.g. refactoring
  # - bugfix         # fixes a defect
  # - test           # fixes/modifies tests
  # - maintenance    # not directly related to the code
  # - release        # related to a new release preparation
  # - documentation  # change in code docs, haddocks...
```

# Context

We previously defined two separate type families `ShelleyLedgerEra` and `CardanoLedgerEra` but never use `CardanoLedgerEra` anywhere.

`ShelleyLedgerEra` is basically the same as `CardanoLedgerEra` except Byron is missing.

There is no reason to have two type families because `CardanoLedgerEra` works everywhere `ShelleyLedgerEra` currently does.

This PR merges the two type families in the one `LedgerEra` type family (which includes Byron) which shortens the name.

Doing this opens the possibility of unifying Byron with the other eras for the minimal set of operations we care to maintain for hard forking purposes.

# How to trust this PR

Highlight important bits of the PR that will make the review faster. If there are commands the reviewer can run to observe the new behavior, describe them.

# Checklist

- [ ] Commit sequence broadly makes sense and commits have useful messages
- [ ] New tests are added if needed and existing tests are updated. See [Running tests](https://github.com/input-output-hk/cardano-node-wiki/wiki/Running-tests) for more details
- [ ] Self-reviewed the diff

2023-11-09 15:58 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Eon/ShelleyBasedEra.hs
> -  ShelleyLedgerEra ConwayEra  = Consensus.StandardConway
Delete this.  Use `LedgerEra` instead.

2023-11-09 15:59 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Eras/Core.hs
> +  LedgerEra ConwayEra  = L.ConwayEra  L.StandardCrypto
Rename `CardanoLedgerEra` which is never used to `LedgerEra` which we use everywhere in place of `ShelleyLedgerEra`.

2023-11-10 11:09 UTC, smelc approved these changes
LGTM :+1:

2023-11-10 11:12 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Eras/Core.hs
> +  LedgerEra ConwayEra  = L.ConwayEra  L.StandardCrypto
I think the change is pretty harmless, but can you check if anything breaks in `cardano-cli`?

2023-11-10 11:12 UTC, carbolymer approved these changes

2023-11-10 12:38 UTC, newhoggy commented on cardano-api/internal/Cardano/Api/Eras/Core.hs
> +  LedgerEra ConwayEra  = L.ConwayEra  L.StandardCrypto
Yep.  Already checked.

2023-11-10 13:11 UTC, Jimbo4350 requested changes
This is not the direction we are taking cardano-api in. We do not care about all the eras, only mainnet and the upcoming era. The first step in this is to factor out the Byron era and only be concerned with shelley based eras. Consolidating the shelley based eras with cardano eras is moving in the wrong direction and prolongs this eventual separation.

2023-11-11 02:29 UTC, newhoggy commented
It's worth noting that this PR doesn't commit us to a particular direction.  On it's own it serves as a straightforward simplification. with the only impact on the rest of the code being a rename and removing a type we don't use anywhere.

2023-11-16 12:49 UTC, Jimbo4350 requested changes
This is an unnecessary change. It is also incorrect because it implies the existence of types in Byron that do no exist. We will be able to simply things further after the Byron related code is isolated.

2023-11-16 13:32 UTC, newhoggy commented
What type is Byron type is being implied that doesn't exist?

2023-11-16 13:58 UTC, closed without merging