Introduce `FileDoesNotExistError` and bump to ouroboros-consensus 0.8
input-output-hk/cardano-api pull request #45
Opened 2023-06-12 17:48 UTC by bolt12

# Description

This PR is related to https://github.com/input-output-hk/ouroboros-consensus/pull/140 and is needed in order for https://github.com/input-output-hk/cardano-node/pull/4024 to compile.

# Changelog

```yaml
- description: |
    Introduce `FileDoesNotExistError`
  # no-changes: the API has not changed
  # compatible: the API has changed but is non-breaking
  # breaking: the API has changed in a breaking way
  compatibility: breaking
  feature: Introduces `FileDoesNotExistError`
  maintenance: Make code type check according to dependency bump changes
  # bugfix: the change fixes a bug in the API
  # test: the change fixes modifies tests
  # maintenance: the change involves something other than the API
  # If more than one is applicable, it may be put into a list.
  type: feature
```

2023-06-22 14:57 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/Error.hs
> +  if fileExists then do
redundant `do`

2023-06-22 14:58 UTC, carbolymer reviewed
Can you reformat changed files, please?

@newhoggy @Jimbo4350 It would be nice if you could have a look too.

2023-06-27 16:44 UTC, bolt12 commented on cardano-api/internal/Cardano/Api/Error.hs
> +  if fileExists then do
Thank you @carbolymer sorry for the delay!

2023-06-30 16:23 UTC, bolt12 commented
Bump @carbolymer

2023-07-03 13:45 UTC, coot commented on cabal.project
> +-- Needed because consensus uses it
I don't see it current `main` branch.

2023-07-03 13:46 UTC, coot commented on cabal.project
> +    ouroboros-consensus-protocol
Maybe move this to `cabal.project.local` branch?

Have you asked Damian to release new version of `consensus` packages?

2023-07-03 13:50 UTC, coot commented on cardano-api/internal/Cardano/Api/Error.hs
> +                else throwError (FileDoesNotExistError fp)
Or use `FileIOError fp $ mkIOError doesNotExistErrorType Nothing (Just fp)`.

2023-07-03 13:58 UTC, coot commented on cardano-api/internal/Cardano/Api/Protocol.hs
> +reflBlockType _                _                = Nothing
```suggestion
reflBlockType ByronBlockType   ByronBlockType   = Just Refl
reflBlockType ShelleyBlockType ShelleyBlockType = Just Refl
reflBlockType CardanoBlockType CardanoBlockType = Just Refl
reflBlockType _                _                = Nothing
```

2023-07-03 14:10 UTC, bolt12 commented on cabal.project
> +-- Needed because consensus uses it
It appears they updated it and no longer require this

2023-07-03 14:19 UTC, bolt12 commented on cardano-api/internal/Cardano/Api/Error.hs
> +                else throwError (FileDoesNotExistError fp)
I prefer the explicit error constructor, it makes it more obvious when pattern matching. 
Matching on `IOException` feels wrong.

2023-07-06 09:02 UTC, carbolymer commented on cardano-api/internal/Cardano/Api/IO.hs
> +    Just fp -> fileIOExceptT (unFile fp) (`BS.writeFile` bs)
If the target file does not exist here, instead of creating the file, `fileIOExceptT` will "throw" `FileDoesNotExist` error.

2023-07-06 09:06 UTC, carbolymer requested changes
https://github.com/input-output-hk/cardano-api/pull/45/files#r1254150882

2023-07-06 09:39 UTC, bolt12 commented on cardano-api/internal/Cardano/Api/IO.hs
> +    Just fp -> fileIOExceptT (unFile fp) (`BS.writeFile` bs)
To be honest, I don't think that's what was happening before

2023-07-06 14:08 UTC, carbolymer approved these changes

2023-07-06 14:18 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Error.hs
> +fileIOExceptT :: MonadIO m
Is this necessary to accommodate the consensus API changes?

2023-07-06 14:22 UTC, Jimbo4350 commented on cardano-api/internal/Cardano/Api/Error.hs
> +                else throwError (FileDoesNotExistError fp)
Please go with @coot's suggestion. This will result in further changes in cardano-cli and this PR should strictly have changes necessary to consensus api changes. If you want to do a refactor, open a separate PR please.

2023-07-06 14:27 UTC, bolt12 commented on cardano-api/internal/Cardano/Api/Error.hs
> +                else throwError (FileDoesNotExistError fp)
This PR is meant to introduce this new constructor and accommodate consensus change. It is my fault it is badly named. I need this new constructor for: https://github.com/input-output-hk/cardano-node/pull/4024 which why I opened it in the first place.
I would prefer not to open a separate PR to do this in 2 steps, if that's okay. See: https://github.com/input-output-hk/cardano-node/pull/4024/files#diff-1edb66cda04d5a388f8de628b2bb28175e079f697559b96cdd0f242b2ec634caR610

2023-07-06 15:58 UTC, Jimbo4350 approved these changes

2023-07-10 08:28 UTC, bolt12 commented
Closed in favor of #99

2023-07-10 08:28 UTC, closed without merging